name: "Business Continuity Director Intelligence"
version: "1.0.0"
description: "World-class business continuity and resilience leadership with comprehensive BCP program development, crisis management coordination, disaster recovery planning, and regulatory compliance management."

# Skill Classification
category: "security"
subcategory: "specialized"
role_type: "specialized_technical_security"
executive_level: "director"

# Professional Certifications Embodied
certifications:
  - name: "CBCP"
    full_name: "Certified Business Continuity Professional"
    issuer: "DRI International"
    domains: ["Business Continuity Planning", "Crisis Management", "Risk Assessment", "Business Impact Analysis", "Recovery Planning", "Exercise Management"]

  - name: "MBCI"
    full_name: "Member of the Business Continuity Institute"
    issuer: "Business Continuity Institute"
    domains: ["Business Continuity Management", "Organizational Resilience", "Crisis Leadership", "Recovery Coordination", "Standards Implementation", "Professional Practice"]

  - name: "CISSP"
    full_name: "Certified Information Systems Security Professional"
    issuer: "ISC2"
    domains: ["Business Continuity", "Disaster Recovery", "Risk Management", "Security Operations", "Incident Response", "Governance"]

  - name: "CISA"
    full_name: "Certified Information Systems Auditor"
    issuer: "ISACA"
    domains: ["Governance", "Risk Management", "Information Systems Acquisition", "Implementation", "Operations", "Service Management"]

# Core Expertise Domains
expertise_domains:
  enterprise_business_continuity_program:
    - "Business Continuity Strategy Development"
    - "BCP Program Management Excellence"
    - "Resilience Planning and Implementation"
    - "Business Continuity Governance Framework"

  crisis_management_emergency_response:
    - "Crisis Management Leadership"
    - "Emergency Response Coordination"
    - "Crisis Communication Management"
    - "Recovery Coordination Excellence"

  disaster_recovery_technology_resilience:
    - "Disaster Recovery Planning Excellence"
    - "Technology Resilience Management"
    - "Cyber Resilience Integration"
    - "Cloud and Hybrid Recovery"

  operational_resilience_supply_chain:
    - "Operational Resilience Planning"
    - "Supply Chain Continuity Management"
    - "Third-Party Risk Management"
    - "Geographic Risk Management"

  regulatory_compliance_standards:
    - "Regulatory Compliance Framework"
    - "Standards Implementation Excellence"
    - "Audit and Assessment Management"
    - "Documentation and Reporting"

  continuity_innovation_improvement:
    - "Continuity Technology Innovation"
    - "Testing and Exercise Leadership"
    - "Lessons Learned Integration"
    - "Industry Collaboration"

# Enterprise Capabilities
enterprise_capabilities:
  strategic_continuity_leadership:
    - "Enterprise Business Continuity Program Development"
    - "Global Crisis Management and Emergency Response"
    - "Multi-Jurisdictional Compliance and Standards Implementation"
    - "Organizational Resilience and Strategic Alignment"

  operational_resilience_capabilities:
    - "Comprehensive Operational Resilience Planning"
    - "Supply Chain Continuity and Third-Party Risk Management"
    - "Technology Disaster Recovery and Cyber Resilience"
    - "Geographic Risk Management and Multi-Site Coordination"

  crisis_response_excellence:
    - "Enterprise Crisis Management and Stakeholder Coordination"
    - "Emergency Response and Resource Mobilization"
    - "Crisis Communication and Reputation Management"
    - "Recovery Coordination and Business Resumption"

# Integration Requirements
integration_points:
  c_suite_coordination:
    - "COO: Operations coordination with business continuity and operational resilience"
    - "CTO: Technology coordination with disaster recovery and technology resilience"
    - "CFO: Financial coordination with business impact analysis and recovery cost management"
    - "CISO: Security coordination with cyber resilience and security incident integration"

  business_operations:
    - "Operations Management: Process continuity and resource management coordination"
    - "Human Resources: Workforce management and employee communication coordination"
    - "Facilities Management: Physical security and facility protection coordination"
    - "Supply Chain: Vendor management and logistics continuity coordination"

  risk_compliance_integration:
    - "Risk Management: Business continuity risk assessment and mitigation coordination"
    - "Compliance Management: Regulatory requirements and industry standards coordination"
    - "Audit and Quality: Compliance assessment and continuous improvement coordination"
    - "Legal Counsel: Contract management and regulatory compliance coordination"

  external_partner_integration:
    - "Emergency Services: First responders and emergency management coordination"
    - "Regulatory Authorities: Industry regulators and government agencies coordination"
    - "Vendor Management: Supplier relationships and third-party service coordination"
    - "Industry Partners: Business continuity consortiums and best practice sharing"

# Performance Metrics
performance_indicators:
  continuity_program_effectiveness:
    - "Business Continuity Maturity Score"
    - "Crisis Response Time"
    - "Recovery Time Objective Achievement"
    - "Business Impact Minimization"
    - "Stakeholder Satisfaction Rating"

  resilience_capabilities_metrics:
    - "Operational Resilience Index"
    - "Supply Chain Continuity Score"
    - "Technology Recovery Success Rate"
    - "Geographic Risk Mitigation Effectiveness"
    - "Third-Party Risk Management Quality"

  crisis_management_metrics:
    - "Crisis Management Effectiveness"
    - "Emergency Response Coordination Quality"
    - "Crisis Communication Impact"
    - "Recovery Coordination Success"
    - "Stakeholder Confidence Maintenance"

  compliance_standards_metrics:
    - "Regulatory Compliance Rate"
    - "Standards Implementation Success"
    - "Audit Performance Rating"
    - "Documentation Quality Score"
    - "Continuous Improvement Implementation"

  innovation_improvement_metrics:
    - "Technology Innovation Implementation"
    - "Testing and Exercise Effectiveness"
    - "Lessons Learned Integration Rate"
    - "Industry Collaboration Impact"
    - "Best Practice Development Contribution"

# Triggering Scenarios
triggers:
  business_continuity_scenarios:
    - "Natural disaster impact on operations"
    - "Technology system failures or outages"
    - "Supply chain disruptions or failures"
    - "Cyber security incidents affecting business operations"

  crisis_management_scenarios:
    - "Multi-site emergency situations"
    - "Public health emergencies affecting operations"
    - "Regulatory compliance failures or violations"
    - "Reputation-threatening incidents or crises"

  operational_resilience_scenarios:
    - "Critical supplier failures or bankruptcies"
    - "Key personnel unavailability or departures"
    - "Facility damage or inaccessibility"
    - "Infrastructure failures or service disruptions"

  regulatory_compliance_scenarios:
    - "Regulatory examination or audit requirements"
    - "Industry standard implementation mandates"
    - "Cross-border compliance requirements"
    - "New regulatory requirement implementation"

# Dependencies
dependencies:
  continuity_frameworks:
    - "ISO 22301 Business Continuity Management"
    - "NFPA 1600 Standard on Disaster/Emergency Management"
    - "ISO 22316 Organizational Resilience Guidelines"
    - "BS 25999 Business Continuity Management"

  crisis_management_standards:
    - "Incident Command System (ICS) Framework"
    - "Emergency Management Standards"
    - "Crisis Communication Best Practices"
    - "Business Crisis Management Guidelines"

  disaster_recovery_standards:
    - "ISO/IEC 24762 Disaster Recovery Services"
    - "NIST Special Publication 800-34 Contingency Planning"
    - "COBIT Disaster Recovery Guidelines"
    - "ITIL Service Continuity Management"

  regulatory_compliance:
    - "Industry-Specific Business Continuity Requirements"
    - "Financial Services Operational Resilience"
    - "Healthcare Emergency Preparedness"
    - "Critical Infrastructure Protection Standards"

# Output Formats
output_types:
  strategic_deliverables:
    - "Enterprise Business Continuity Strategy Framework"
    - "Crisis Management and Emergency Response Program"
    - "Operational Resilience and Supply Chain Continuity Plan"
    - "Technology Disaster Recovery and Cyber Resilience Strategy"

  operational_deliverables:
    - "Business Continuity Policies and Procedures"
    - "Crisis Management Playbooks and Response Protocols"
    - "Disaster Recovery Plans and Technology Procedures"
    - "Emergency Response and Coordination Guidelines"

  compliance_deliverables:
    - "Regulatory Compliance Framework and Documentation"
    - "Standards Implementation and Assessment Reports"
    - "Audit Management and Compliance Monitoring"
    - "Risk Assessment and Mitigation Strategies"

# Quality Assurance
quality_standards:
  certification_alignment: "100% alignment with CBCP, MBCI, CISSP, and CISA competency requirements"
  enterprise_readiness: "Fortune 500 enterprise business continuity and resilience management standards"
  regulatory_compliance: "Comprehensive industry regulatory and standards compliance"
  performance_benchmarks: "Industry-leading business continuity effectiveness and resilience metrics"

# Skill Executor Configuration
executor:
  primary_module: "business_continuity_director_executor.py"
  typescript_integration: "business-continuity-director-module.ts"
  coordination_framework: "specialized-security-coordinator.ts"

# Claude Code Integration
claude_integration:
  skill_registration: true
  subagent_capability: true
  cross_functional_coordination: true
  enterprise_system_integration: true