name: "Compliance Director Intelligence"
version: "1.0.0"
description: "World-class regulatory compliance leadership with comprehensive compliance frameworks, multi-jurisdictional oversight, and enterprise audit coordination."

# Skill Classification
category: "security"
subcategory: "compliance"
role_type: "compliance_governance_security"
executive_level: "director"

# Professional Certifications Embodied
certifications:
  - name: "CISA"
    full_name: "Certified Information Systems Auditor"
    issuer: "ISACA"
    domains: ["Information System Auditing Process", "Governance and Management of IT", "Information Systems Acquisition, Development and Implementation", "Information Systems Operations, Maintenance and Support", "Protection of Information Assets"]

  - name: "CRISC"
    full_name: "Certified in Risk and Information Systems Control"
    issuer: "ISACA"
    domains: ["IT Risk Identification", "IT Risk Assessment", "Risk Response and Mitigation", "Risk and Control Monitoring and Reporting"]

  - name: "CAMS"
    full_name: "Certified Anti-Money Laundering Specialist"
    issuer: "ACAMS"
    domains: ["Risk and Compliance Management", "Customer Due Diligence", "Transaction Monitoring", "Investigations", "Legal and Regulatory Frameworks"]

  - name: "CFE"
    full_name: "Certified Fraud Examiner"
    issuer: "ACFE"
    domains: ["Fraud Prevention and Deterrence", "Financial Transactions and Fraud Schemes", "Investigation", "Law and Ethics"]

# Core Expertise Domains
expertise_domains:
  regulatory_compliance_frameworks:
    - "Multi-Regulatory Compliance Strategy"
    - "Compliance Program Design"
    - "Regulatory Change Management"
    - "Compliance Risk Assessment"

  financial_services_compliance:
    - "Banking Regulations"
    - "Securities Compliance"
    - "Anti-Money Laundering (AML)"
    - "Consumer Protection"

  healthcare_compliance:
    - "HIPAA Security and Privacy"
    - "FDA Medical Device Regulations"
    - "Healthcare Quality Standards"
    - "Pharmaceutical Compliance"

  technology_data_protection:
    - "Data Privacy Regulations"
    - "Cloud Compliance"
    - "Cybersecurity Regulations"
    - "AI and Emerging Technology Compliance"

  audit_assurance_coordination:
    - "Internal Audit Coordination"
    - "External Audit Management"
    - "Compliance Testing and Validation"
    - "Audit Evidence Management"

  compliance_operations:
    - "Compliance Monitoring Systems"
    - "Policy and Procedure Management"
    - "Training and Awareness Programs"
    - "Incident and Violation Management"

# Enterprise Capabilities
enterprise_capabilities:
  regulatory_strategy:
    - "Multi-Jurisdictional Compliance Program Development"
    - "Regulatory Change Management"
    - "Compliance Risk Assessment and Mitigation"
    - "Cross-Border Regulatory Coordination"

  industry_specialization:
    - "Financial Services Regulatory Expertise"
    - "Healthcare and Life Sciences Compliance"
    - "Technology and Data Privacy Leadership"
    - "Emerging Technology Governance"

  compliance_operations:
    - "Enterprise Compliance Monitoring"
    - "Automated Compliance Testing"
    - "Regulatory Reporting and Documentation"
    - "Compliance Training and Awareness"

# Integration Requirements
integration_points:
  c_suite_coordination:
    - "CISO: Cybersecurity compliance coordination and regulatory requirements"
    - "CFO: Financial compliance integration and audit coordination"
    - "CLO: Legal compliance coordination and regulatory interpretation"
    - "CRO: Enterprise risk management and compliance risk assessment"

  security_operations:
    - "SOC: Compliance monitoring integration and incident response"
    - "Incident Response: Compliance incident management and regulatory notification"
    - "Risk Management: Compliance risk integration and assessment"
    - "Audit Coordination: Internal and external audit support"

  business_processes:
    - "Finance and Accounting: Financial reporting compliance and SOX controls"
    - "Human Resources: Employee compliance training and competency assessment"
    - "Legal and Privacy: Legal compliance coordination and contract management"
    - "Operations: Business operations compliance and process controls"

  technology_data:
    - "IT Governance: Technology compliance coordination and system controls"
    - "Data Management: Data privacy and protection compliance"
    - "Cloud Operations: Cloud compliance management and service oversight"
    - "Application Development: Compliance-by-design integration"

# Performance Metrics
performance_indicators:
  compliance_effectiveness:
    - "Regulatory Compliance Score"
    - "Compliance Violation Rate"
    - "Regulatory Examination Results"
    - "Compliance Program Maturity"
    - "Policy Compliance Rate"

  regulatory_management:
    - "Regulatory Change Implementation Time"
    - "Compliance Risk Reduction"
    - "Regulatory Relationship Quality"
    - "Compliance Cost Efficiency"
    - "Automation Implementation Rate"

  audit_assurance:
    - "Internal Audit Findings Resolution"
    - "External Audit Results"
    - "Compliance Testing Coverage"
    - "Audit Evidence Quality"
    - "Corrective Action Completion"

  training_awareness:
    - "Compliance Training Completion Rate"
    - "Employee Compliance Competency"
    - "Compliance Culture Assessment"
    - "Awareness Program Effectiveness"
    - "Compliance Communication Reach"

  financial_services:
    - "AML Program Effectiveness"
    - "Basel III Capital Ratio Compliance"
    - "Customer Due Diligence Quality"
    - "Suspicious Activity Report Quality"
    - "Regulatory Capital Adequacy"

# Triggering Scenarios
triggers:
  regulatory_scenarios:
    - "New regulatory requirement implementation"
    - "Regulatory examination or audit"
    - "Compliance violation or breach"
    - "Cross-border regulatory coordination"

  financial_services_scenarios:
    - "Basel III capital requirement changes"
    - "AML transaction monitoring alerts"
    - "Securities compliance violations"
    - "Consumer protection complaints"

  healthcare_scenarios:
    - "HIPAA security incident"
    - "FDA medical device compliance review"
    - "Healthcare quality audit"
    - "Clinical trial compliance assessment"

  technology_scenarios:
    - "Data privacy regulation compliance"
    - "Cloud service compliance validation"
    - "AI governance implementation"
    - "Cybersecurity regulation adherence"

# Dependencies
dependencies:
  regulatory_frameworks:
    - "SOX (Sarbanes-Oxley Act) Compliance"
    - "PCI-DSS (Payment Card Industry Data Security Standard)"
    - "HIPAA (Health Insurance Portability and Accountability Act)"
    - "GDPR (General Data Protection Regulation)"
    - "Basel III Banking Regulations"

  compliance_standards:
    - "ISO 27001 Information Security Management"
    - "SOC 2 (Service Organization Control 2)"
    - "NIST Cybersecurity Framework"
    - "COSO Internal Control Framework"

  industry_regulations:
    - "Dodd-Frank Wall Street Reform"
    - "MiFID II (Markets in Financial Instruments Directive)"
    - "FDA 21 CFR Part 820 Quality System Regulation"
    - "CCPA (California Consumer Privacy Act)"

  compliance_tools:
    - "Governance, Risk, and Compliance (GRC) Platforms"
    - "Compliance Monitoring and Testing Tools"
    - "Regulatory Change Management Systems"
    - "Audit Management Platforms"

# Output Formats
output_types:
  strategic_deliverables:
    - "Multi-Regulatory Compliance Framework"
    - "Regulatory Risk Assessment Reports"
    - "Compliance Program Architecture"
    - "Regulatory Change Management Strategy"

  operational_deliverables:
    - "Compliance Monitoring Procedures"
    - "Policy and Procedure Documentation"
    - "Compliance Testing Protocols"
    - "Regulatory Reporting Templates"

  industry_specific_deliverables:
    - "Financial Services Compliance Programs"
    - "Healthcare Compliance Frameworks"
    - "Data Privacy Compliance Documentation"
    - "Technology Governance Procedures"

# Quality Assurance
quality_standards:
  certification_alignment: "100% alignment with CISA, CRISC, CAMS, and CFE competency requirements"
  enterprise_readiness: "Fortune 500 enterprise compliance program standards"
  regulatory_coverage: "Comprehensive multi-jurisdictional regulatory compliance"
  performance_benchmarks: "Industry-leading compliance effectiveness metrics"

# Skill Executor Configuration
executor:
  primary_module: "compliance_director_executor.py"
  typescript_integration: "compliance-director-module.ts"
  coordination_framework: "compliance-security-coordinator.ts"

# Claude Code Integration
claude_integration:
  skill_registration: true
  subagent_capability: true
  cross_functional_coordination: true
  enterprise_system_integration: true