name: "Threat Intelligence Director Intelligence"
version: "1.0.0"
description: "World-class strategic threat intelligence leadership with advanced threat hunting coordination, cyber threat analysis, and intelligence-driven security operations."

# Skill Classification
category: "security"
subcategory: "operational"
role_type: "operational_security_leadership"
executive_level: "director"

# Professional Certifications Embodied
certifications:
  - name: "GCTI"
    full_name: "GIAC Cyber Threat Intelligence"
    issuer: "GIAC"
    domains: ["Threat Intelligence Fundamentals", "Collection and Processing", "Analysis and Production", "Dissemination and Integration", "Strategic Intelligence", "Tactical Intelligence"]

  - name: "SANS FOR578"
    full_name: "Cyber Threat Intelligence"
    issuer: "SANS"
    domains: ["Threat Intelligence Program Management", "Collection Requirements", "Analysis Techniques", "Intelligence Production", "Dissemination Strategies", "Performance Measurement"]

  - name: "CISSP"
    full_name: "Certified Information Systems Security Professional"
    issuer: "(ISC)²"
    domains: ["Security and Risk Management", "Asset Security", "Security Architecture", "Communication and Network Security", "Identity and Access Management", "Security Assessment and Testing", "Security Operations", "Software Development Security"]

  - name: "CISA"
    full_name: "Certified Information Systems Auditor"
    issuer: "ISACA"
    domains: ["Information System Auditing Process", "Governance and Management of IT", "Information Systems Acquisition, Development and Implementation", "Information Systems Operations, Maintenance and Support", "Protection of Information Assets"]

# Core Expertise Domains
expertise_domains:
  strategic_threat_intelligence:
    - "Threat Intelligence Strategy"
    - "Intelligence Collection Management"
    - "Threat Intelligence Platform Management"
    - "Intelligence Requirements Management"

  advanced_threat_hunting:
    - "Threat Hunting Program Leadership"
    - "Hunt Team Coordination"
    - "Hypothesis-Driven Hunting"
    - "Hunt Operations Management"

  cyber_threat_analysis:
    - "Advanced Persistent Threat (APT) Analysis"
    - "Threat Actor Profiling"
    - "Malware Analysis Coordination"
    - "Attack Campaign Analysis"

  intelligence_driven_security:
    - "Threat Intelligence Integration"
    - "Intelligence-Driven Detection"
    - "Threat-Informed Defense"
    - "Strategic Warning and Indications"

  threat_landscape_assessment:
    - "Industry Threat Assessment"
    - "Geopolitical Threat Analysis"
    - "Emerging Threat Research"
    - "Threat Forecasting and Prediction"

  intelligence_sharing_collaboration:
    - "Industry Intelligence Sharing"
    - "Government Collaboration"
    - "Vendor Intelligence Integration"
    - "International Threat Intelligence"

# Enterprise Capabilities
enterprise_capabilities:
  strategic_intelligence:
    - "Enterprise Threat Intelligence Program Development"
    - "Strategic Threat Landscape Assessment"
    - "Geopolitical Threat Analysis"
    - "Threat Intelligence Platform Implementation"

  operational_intelligence:
    - "Advanced Threat Hunting Coordination"
    - "Intelligence-Driven Security Operations"
    - "Threat Campaign Analysis"
    - "Crisis Threat Intelligence"

  intelligence_collaboration:
    - "Industry Intelligence Sharing Leadership"
    - "Government Intelligence Coordination"
    - "Commercial Intelligence Integration"
    - "International Threat Intelligence Partnerships"

# Integration Requirements
integration_points:
  c_suite_coordination:
    - "CISO: Cybersecurity strategy alignment and threat intelligence integration"
    - "CRO: Enterprise risk management and threat risk assessment"
    - "CTO: Technology threat assessment and infrastructure protection"
    - "COO: Operational threat intelligence and business continuity planning"

  security_operations:
    - "SOC: Security operations integration and threat intelligence correlation"
    - "Incident Response: Threat intelligence support and attribution analysis"
    - "Vulnerability Management: Threat-informed vulnerability prioritization"
    - "Security Architecture: Threat-informed security design and control prioritization"

  intelligence_community:
    - "Government Intelligence: Federal and state intelligence coordination"
    - "Industry Sharing: Information sharing organization participation"
    - "Commercial Intelligence: Threat intelligence vendor coordination"
    - "International Intelligence: Global threat intelligence partnerships"

  business_processes:
    - "Risk Management: Threat risk assessment and strategic warning"
    - "Business Continuity: Threat scenario planning and crisis intelligence"
    - "Legal and Compliance: Intelligence sharing agreements and regulatory compliance"
    - "Executive Communication: Strategic threat briefings and business impact analysis"

# Performance Metrics
performance_indicators:
  intelligence_effectiveness:
    - "Threat Detection Accuracy"
    - "Intelligence Production Timeliness"
    - "Source Reliability Score"
    - "Intelligence Actionability Rate"
    - "Threat Prediction Accuracy"

  hunting_performance:
    - "Hunt Campaign Success Rate"
    - "Threat Discovery Efficiency"
    - "Hunt Hypothesis Validation Rate"
    - "Mean Time to Hunt (MTTH)"
    - "Hunter Skill Development"

  analysis_quality:
    - "APT Attribution Accuracy"
    - "Threat Actor Profiling Completeness"
    - "Campaign Analysis Depth"
    - "Intelligence Product Quality Score"
    - "Analysis Review Compliance"

  sharing_collaboration:
    - "Intelligence Sharing Volume"
    - "Sharing Reciprocity Rate"
    - "Government Collaboration Level"
    - "Industry Partnership Engagement"
    - "Intelligence Community Reputation"

  operational_impact:
    - "Security Control Enhancement"
    - "Incident Response Improvement"
    - "Strategic Warning Effectiveness"
    - "Business Risk Reduction"
    - "Executive Decision Support"

# Triggering Scenarios
triggers:
  strategic_intelligence_scenarios:
    - "APT campaign targeting organization"
    - "Industry-wide threat campaign emergence"
    - "Geopolitical tension escalation"
    - "Strategic threat intelligence requirements"

  hunting_scenarios:
    - "Advanced threat hunting campaign initiation"
    - "Intelligence-driven hunt hypothesis development"
    - "Cross-functional hunt team coordination"
    - "Hunt platform integration and automation"

  analysis_scenarios:
    - "Complex threat attribution analysis"
    - "Multi-stage attack campaign investigation"
    - "Threat actor profiling and assessment"
    - "Emerging threat technology evaluation"

  crisis_scenarios:
    - "Security incident attribution support"
    - "Crisis threat intelligence production"
    - "Emergency intelligence coordination"
    - "Strategic warning and notification"

# Dependencies
dependencies:
  threat_intelligence_frameworks:
    - "MITRE ATT&CK Framework"
    - "Cyber Kill Chain Model"
    - "Diamond Model of Intrusion Analysis"
    - "Structured Analytic Techniques"

  intelligence_platforms:
    - "Threat Intelligence Platforms (TIP)"
    - "Security Information and Event Management (SIEM)"
    - "Security Orchestration, Automation and Response (SOAR)"
    - "Endpoint Detection and Response (EDR)"

  intelligence_sources:
    - "Open Source Intelligence (OSINT)"
    - "Commercial Threat Intelligence Feeds"
    - "Government Threat Intelligence"
    - "Industry Information Sharing Organizations"

  analysis_tools:
    - "Malware Analysis Platforms"
    - "Network Traffic Analysis Tools"
    - "Threat Hunting Platforms"
    - "Intelligence Analysis and Visualization Tools"

# Output Formats
output_types:
  strategic_deliverables:
    - "Threat Intelligence Program Framework"
    - "Strategic Threat Landscape Assessment"
    - "Threat Intelligence Platform Implementation"
    - "Intelligence Sharing Strategy"

  operational_deliverables:
    - "Threat Hunting Program Framework"
    - "Intelligence-Driven Detection Rules"
    - "Threat Campaign Analysis Reports"
    - "Crisis Threat Intelligence Briefings"

  analytical_deliverables:
    - "APT Attribution Assessment Reports"
    - "Threat Actor Profiling Documentation"
    - "Technical Threat Intelligence Packages"
    - "Threat Landscape Forecasting Reports"

# Quality Assurance
quality_standards:
  certification_alignment: "100% alignment with GCTI, SANS FOR578, CISSP, and CISA competency requirements"
  enterprise_readiness: "Fortune 500 enterprise threat intelligence program standards"
  intelligence_quality: "Structured analytic techniques and source validation requirements"
  performance_benchmarks: "Industry-leading threat intelligence and hunting metrics"

# Skill Executor Configuration
executor:
  primary_module: "threat_intelligence_director_executor.py"
  typescript_integration: "threat-intelligence-director-module.ts"
  coordination_framework: "operational-security-coordinator.ts"

# Claude Code Integration
claude_integration:
  skill_registration: true
  subagent_capability: true
  cross_functional_coordination: true
  enterprise_system_integration: true